drivers: input: keyboard: fix missing type specifier
kernel/nubia/sdm845/drivers/input/keyboard/gpio_keys.c:384:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
        static gs_old_state;
        ~~~~~~ ^
        int
1 error generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Iddf0d68344f3001855ed6132a4da26cf124289fc